name: Build LLVM

on: [push, pull_request]

jobs:
  build-llvm-x86_64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: sudo apt-get -y install g++ python3 ninja-build
    - name: Build llvm
      run: ./scripts/build.sh
  build-llvm-aarch64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: sudo apt-get -y install g++ python3 ninja-build g++-aarch64-linux-gnu
    - name: Build llvm
      run: ./scripts/build_cross_aarch64.sh
